# Generated by Django 3.1.2 on 2020-10-21 07:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('document_no', models.CharField(max_length=50)),
                ('summed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_register.suplier')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_register.expensetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(summed__gt=Decimal('0.01')), name='summed_gt_0.1'),
        ),
    ]
