# Generated by Django 3.1.2 on 2020-10-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suplier',
            old_name='type_name',
            new_name='supplier_name',
        ),
    ]
