# Generated by Django 3.1.2 on 2020-10-21 10:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_register', '0002_auto_20201021_0756'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expense',
            name='summed_gt_0.1',
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(summed__gt=Decimal('0.00')), name='summed should be higher than 0.00'),
        ),
    ]
